### ISSUE TITLE
Low compiler compatibility due to to_chars / Elementary string conversions (+ floating point)

### ISSUE THREAD

**Issue by comment-out** [ttsuki/nanojson#2]
https://en.cppreference.com/w/cpp/compiler_support/17
Compiler support for the [Elementary string conversions](https://en.cppreference.com/w/cpp/utility#Elementary_string_conversions)* feature is currently limited to gcc 11 and MSVC 19.24.
I'm unable to compile nanojson2 with Debian 11's clang and gcc packages.
gcc 11 is not available in Debian 11.
> The Debian 11 Hard Freeze was on [2021-03-12](https://wiki.debian.org/DebianBullseye), which happens to be in between the release of [clang-11](https://releases.llvm.org/) and [gcc-11](https://gcc.gnu.org/releases.html)

```
$ cat /etc/debian_version
11.3

$ g++ --version
g++ (Debian 10.2.1-6) 10.2.1 20210110

$ clang++-11 --version
Debian clang version 11.0.1-2
```

**Comment by ttsuki** [comment]
Thank you for opening issue.

Yes, [currently, nanojson2 needs an STL that fully supports P0067R5 (`to_chars`/`from_chars` with FP)](https://github.com/ttsuki/nanojson/blob/099a232af0207de017c7c48230a7999014984e9b/nanojson2.h#L48), e.g. libstdc++-11.

I've been considering a fallback implementation using `std::stringstream`, but not implemented yet.

**Comment by ttsuki** [comment]
Please try #3.

**Comment by comment-out** [comment]
Thanks, it compiles and runs successfully with gcc and clang.
Here is the sample binary output (matches on both compilers)
[example_output.txt](https://github.com/ttsuki/nanojson/files/9154098/example_output.txt)

Additionally, here's a .gitignore diff for ignoring CMake files.
```diff
diff --git a/.gitignore b/.gitignore
index 8ae252a..df87500 100644
--- a/.gitignore
+++ b/.gitignore
@@ -1,2 +1,11 @@
 /.vs
 /out
+
+# cmake
+CMakeCache.txt
+CMakeFiles/
+cmake_install.cmake
+Makefile
+
+# sample binary
+nanojson2
```
